name: bdc
channels:
  - conda-forge
  - bioconda
dependencies:
  - biopython=1.78
  - dask=2022.7.0
  - mpi4py=3.1.4
  - numpy=1.23.3
  - pandas=1.4.4
  - pyspark=3.3.0
  - python=3.10.8
  - scipy=1.9.3
